title: The RSS Tracker Obsidian Plugin
description: User manual for the RSS Tracker Obsidian plugin that tracks RSS feeds and displays them in a note.
theme: jekyll-theme-midnight
favicon: /assets/rss-tracker.png
navigation:
  - name: Home
    url: /index
  - name: Commands
    url: /commands
